import {configureShapeData,checkCharacterShape,normalizeShapeSettings,rulesForCharacter,EXTRA_DEFAULTS} from './shape-rules.mjs';
const $=id=>document.getElementById(id),[components,rules]=await Promise.all(['shape-components','shape-rules'].map(async n=>{const r=await fetch('./data/'+n+'.json');if(!r.ok)throw Error(n);return r.json();}));
configureShapeData(components,rules);
const curriculum=await (await fetch('./data/curriculum.json')).json();
function reference(){return curriculum.glyphs[current].paths.map(d=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);const length=p.getTotalLength();return Array.from({length:64},(_,i)=>{const point=p.getPointAtLength(i*length/63);return {x:point.x,y:point.y};});});}
const chars=Object.values(components.characters).sort((a,b)=>a.grade-b.grade||a.char.codePointAt(0)-b.char.codePointAt(0));let strokes=[],current='見',drawing=null,selection=null;
const canvas=$('ink'),ctx=canvas.getContext('2d');
function fill(){const q=$('search').value,filtered=chars.filter(c=>!q||q.includes(c.char));$('character').replaceChildren();for(const c of filtered){const o=document.createElement('option');o.value=c.char;o.textContent=c.char+'（'+c.grade+'年）';$('character').append(o);}if(filtered.some(c=>c.char===current))$('character').value=current;else if(filtered.length)current=filtered[0].char;}
function entry(){return components.characters[current];}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.scale(6,6);ctx.strokeStyle='#263e38';ctx.lineWidth=1.6;ctx.lineCap='round';ctx.lineJoin='round';for(const line of strokes){ctx.beginPath();line.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();}ctx.restore();$('focus').replaceChildren();if(!selection?.focus)return;const f=selection.focus;
 const add=(tag,attrs)=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);$('focus').append(n);};
 for(const i of f.actualIndices||[]){const line=strokes[i];if(line)add('path',{d:line.map((p,j)=>(j?'L':'M')+p.x+','+p.y).join(' '),stroke:'#dc653a','stroke-width':2.1,fill:'none'});}
 add('circle',{cx:f.point.x,cy:f.point.y,r:f.radius,stroke:'#d3432c','stroke-width':1.2,fill:'none'});for(const p of f.anchors||[f.tip,f.acrossPoint].filter(Boolean))add('circle',{cx:p.x,cy:p.y,r:1.5,fill:'#d3432c'});
}
function evaluate(){selection=null;const settings=normalizeShapeSettings(Object.fromEntries(Object.keys(EXTRA_DEFAULTS).map(k=>[k,$('level').value])));settings.beautySlope='off';const result=checkCharacterShape(current,strokes,reference(),settings,{mode:$('mode').value});$('diagnostics').textContent=JSON.stringify(result,null,2);$('message').textContent='骨組み：'+({pass:'今回の確認項目では問題が見つかりませんでした',fail:'要修正（検証用の候補を含みます）',uncertain:'お手本と比べて自己確認',skipped:'設定でお休み',unavailable:'確かめられませんでした'}[result.status]||result.status);$('issues').replaceChildren();
 for(const row of [...result.checks,...(result.writingChecks||[]),...(result.beautyChecks||[])].sort((a,b)=>(b.id===result.ruleId)-(a.id===result.ruleId))){if(['pass','skipped','unavailable'].includes(row.status))continue;const b=document.createElement('button'),label=document.createElement('span'),meta=document.createElement('small');label.textContent=row.text;meta.textContent=({identity:'骨組み',writing:'書き方',beauty:'美文字'}[row.layer])+'／'+row.status+(row.candidateStatus?'（候補測定：'+row.candidateStatus+'）':'');b.append(label,meta);b.onclick=()=>{selection=row;$('message').textContent=row.text;for(const n of $('issues').children)n.setAttribute('aria-pressed',String(n===b));draw();};$('issues').append(b);if(!selection)selection=row;}draw();
}
function load(){current=$('character').value||current;strokes=structuredClone(reference());selection=null;$('rules').replaceChildren();for(const r of rulesForCharacter(current)){const li=document.createElement('li');li.textContent=r.layer+'：'+r.label+'／'+r.kind+'（'+r.review.status+'）';$('rules').append(li);}$('coverage').textContent='部品 '+entry().components.length+'／実行する規則 '+rulesForCharacter(current).length+'。'+(current==='鉄'?'既存の legacy-iron-v2 を使用。':'追加規則の目視確認待ち。')+'児童の実筆跡による校正は未実施。';evaluate();}
function bar(){return entry().components.find(i=>i.roles['bar-1'])?.roles['bar-1'].stroke-1;}
$('reference').onclick=load;$('missing').onclick=()=>{load();const i=bar();if(Number.isInteger(i)){strokes.splice(i,1);evaluate();}};$('extra').onclick=()=>{load();const i=bar();if(Number.isInteger(i)){strokes.push(strokes[i].map(p=>({...p,y:p.y+5})));evaluate();}};$('retrace').onclick=()=>{load();const i=bar();if(Number.isInteger(i)){strokes.push(structuredClone(strokes[i]));evaluate();}};
$('clear').onclick=()=>{strokes=[];selection=null;$('issues').replaceChildren();$('message').textContent='枠の中に、指やペンで書いてください。';draw();};$('undo').onclick=()=>{strokes.pop();selection=null;draw();};$('check').onclick=evaluate;$('character').onchange=load;$('search').oninput=()=>{fill();if($('character').value)load();};$('level').onchange=evaluate;$('mode').onchange=evaluate;
const point=e=>{const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left)/b.width*109,y:(e.clientY-b.top)/b.height*109};};canvas.onpointerdown=e=>{selection=null;canvas.setPointerCapture(e.pointerId);drawing=[point(e)];strokes.push(drawing);draw();};canvas.onpointermove=e=>{if(drawing){drawing.push(point(e));draw();}};canvas.onpointerup=canvas.onpointercancel=()=>{if(drawing?.length===1)drawing.push({...drawing[0]});drawing=null;};
const fragment=document.createDocumentFragment();for(const c of chars){const tr=document.createElement('tr');for(const v of [c.char,c.grade,c.components.length,rulesForCharacter(c.char).length,c.char==='鉄'?'既存互換／未校正':'目視確認待ち／未校正']){const td=document.createElement('td');td.textContent=v;tr.append(td);}fragment.append(tr);}$('catalog').append(fragment);$('totals').textContent=chars.length+'字、'+chars.reduce((s,c)=>s+rulesForCharacter(c.char).length,0)+'規則の割り当て（鉄の互換規則を含む）。全細部の対応完了を表す数値ではありません。';fill();$('character').value=current;load();
