const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'data/curriculum.json'))),kana=JSON.parse(fs.readFileSync(path.join(root,'data/kana.json')));let browser;
async function draw(page,paths){const strokes=await page.evaluate(ds=>ds.map(d=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);const l=p.getTotalLength();return Array.from({length:25},(_,i)=>{const p2=p.getPointAtLength(l*i/24);return{x:p2.x,y:p2.y};});}),paths);await page.locator('#canvas').scrollIntoViewIfNeeded();const box=await page.locator('#canvas').boundingBox();for(const s of strokes){await page.mouse.move(box.x+s[0].x/109*box.width,box.y+s[0].y/109*box.height);await page.mouse.down();for(const p of s.slice(1))await page.mouse.move(box.x+p.x/109*box.width,box.y+p.y/109*box.height);await page.mouse.up();}}
async function q(page){const id=await page.locator('#masked').getAttribute('data-question-id');const [char,word,reading]=id.split('|');return {char,word,reading};}
(async()=>{
 browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1280,height:1000}});
 await context.addInitScript(()=>{class FakeSpeech{start(){window.testSpeech=this;}abort(){this.onend?.();}}window.SpeechRecognition=FakeSpeech;});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.APP_URL||(process.env.APP_URL||'http://127.0.0.1:8897/'));await page.waitForFunction(()=>document.getElementById('modelStatus').textContent.includes('使えます'),{timeout:120000});
 fs.mkdirSync(path.join(root,'qa'),{recursive:true});await page.screenshot({path:path.join(root,'qa/new-setup.png'),fullPage:true});
 await page.click('[data-scope-mode=units]');await page.locator('input[name=mode][value=read]').check();await page.selectOption('#sessionLength','5');await page.click('#start');assert.equal(await page.locator('#reading').isVisible(),false);assert.equal(await page.locator('#writingBox').isVisible(),false);assert.equal(await page.locator('#check').isDisabled(),true);assert.equal(await page.locator('#masked').evaluate(el=>getComputedStyle(el).writingMode),'vertical-rl');
 let current=await q(page);assert.ok(current);await page.locator('#readingInput').fill(current.reading);await page.click('#check');assert.match(await page.locator('#feedback').innerText(),/はなまる/);let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kanji-hint-drill-v1')));assert.equal(Object.keys(saved.records)[0].endsWith('|read'),true);assert.equal(Object.values(saved.records)[0].correct,1);
 await page.click('#next');current=await q(page);await page.click('#hint');assert.equal(await page.locator('#readingHint path').count(),1);await page.locator('#readingInput').fill(current.reading);await page.click('#check');saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kanji-hint-drill-v1')));assert.ok(Object.values(saved.records).some(x=>x.helped===1));
 await page.click('#next');await page.locator('#readingInput').fill('ぜったいちがう');await page.click('#check');assert.match(await page.locator('#feedback').innerText(),/おしい/);await page.click('#next');current=await q(page);
 await page.click('[data-input=voice]');await page.click('#speak');await page.evaluate(reading=>window.testSpeech.onresult({results:[[{transcript:reading}]]}),current.reading);assert.equal(await page.locator('#readingInput').inputValue(),current.reading);await page.click('#check');assert.match(await page.locator('#feedback').innerText(),/はなまる/);
 await page.click('#next');await page.click('[data-input=handwriting]');await draw(page,kana.glyphs['あ'].paths);await page.click('#kanaCommit');await page.waitForFunction(()=>document.querySelectorAll('#kanaCandidates button').length>0,{timeout:60000});assert.ok((await page.locator('#kanaCandidates button').allTextContents()).includes('あ'));await page.getByRole('button',{name:'あを こたえに いれる',exact:true}).click();assert.equal(await page.locator('#readingInput').inputValue(),'あ');await page.click('#deleteKana');assert.equal(await page.locator('#check').isDisabled(),true);await page.click('#hint');await page.screenshot({path:path.join(root,'qa/new-reading.png'),fullPage:true});
 await page.click('[data-input=voice]');await page.click('#speak');await page.evaluate(()=>window.testSpeech.onerror({error:'not-allowed'}));assert.match(await page.locator('#speechStatus').innerText(),/マイク/);const previous=await page.evaluate(()=>window.testSpeech);await page.click('#back');await page.click('#start');await page.evaluate(()=>window.testSpeech.onresult({results:[[{transcript:'ふるい'}]]}));assert.equal(await page.locator('#readingInput').inputValue(),'');
 await page.click('#back');for(const width of [320,390,768]){await page.setViewportSize({width,height:844});await page.screenshot({path:path.join(root,`qa/new-setup-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`setup overflow ${width}`);await page.click('#start');await page.screenshot({path:path.join(root,`qa/new-reading-${width}.png`),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`reading overflow ${width}`);await page.click('[data-input=handwriting]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.click('#back');}
 await page.click('#verticalToggle');await page.click('#start');assert.equal(await page.locator('#masked').evaluate(el=>getComputedStyle(el).writingMode),'horizontal-tb');await page.click('#back');await page.locator('input[value=write]').check();await page.click('#start');assert.equal(await page.locator('#readingControls').isVisible(),false);assert.equal(await page.locator('#writingBox').isVisible(),true);await draw(page,data.glyphs['一'].paths);if(await page.locator('#hint').isEnabled())await page.click('#hint');assert.ok(await page.locator('#guide path').count()>0);await page.click('#answer');assert.ok(await page.locator('#next').isVisible());
 assert.deepEqual(errors,[]);console.log('PASS: reading keyboard, correct/wrong, mode-separated records, kana hints, real kana model candidates, speech result/error/stale callback, three responsive widths, orientation and write mode');await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1;});
