import assert from 'node:assert/strict';
import {analyzeStrokes,updateRecord,validateProgress} from '../core.mjs';
import {normalizeShapeSettings,DEFAULT_SHAPE_SETTINGS} from '../shape-rules.mjs';
const h=[{x:20,y:50},{x:90,y:50}],v=[{x:50,y:20},{x:50,y:90}];
assert.equal(analyzeStrokes([[...h].reverse()],[h],{direction:'off'}).type,'good');
assert.equal(analyzeStrokes([v,h],[h,v],{order:'off'}).type,'good');
assert.equal(analyzeStrokes([h],[h,v],{count:'off'}).type,'good');
const shifted=h.map(p=>({x:p.x,y:p.y+24}));
assert.equal(analyzeStrokes([shifted],[h],{shape:'relaxed'}).type,'good');
assert.equal(analyzeStrokes([shifted],[h],{shape:'normal'}).type,'shape');
assert.equal(analyzeStrokes([shifted],[h],{shape:'off'}).type,'good');
assert.equal(normalizeShapeSettings({count:'strict'}).count,'normal');
const r=updateRecord(null,{type:'wrong',reason:'protrusion',shapePolicy:'v1;protrusion=strict'},100);
assert.equal(r.correct,0);assert.equal(r.errors,1);assert.equal(r.due,100);
assert.equal(validateProgress({version:1,records:{iron:r}}).records.iron.history[0].shapePolicy,'v1;protrusion=strict');
const old=validateProgress({version:1,records:{iron:{history:[{type:'correct',time:100}]}}});
assert.equal(old.records.iron.history[0].shapePolicy,'');
assert.equal(normalizeShapeSettings({protrusion:'off'}).containment,'normal');
assert.equal(DEFAULT_SHAPE_SETTINGS.sweepEnd,'off');assert.equal(DEFAULT_SHAPE_SETTINGS.beautyParallel,'off');assert.equal(DEFAULT_SHAPE_SETTINGS.beautySlope,'off');
const policy='v2;'+Object.entries(DEFAULT_SHAPE_SETTINGS).map(([k,v])=>k+'='+v).join(';');
assert.ok(policy.length>150);
const beautiful=updateRecord(null,{type:'correct',beautyNotes:['tetsu-sweep-end'],shapePolicy:policy},100);
assert.equal(beautiful.correct,1);assert.equal(beautiful.helped,0);assert.equal(beautiful.streak,1);
const imported=validateProgress({version:1,records:{iron:beautiful}}).records.iron;
assert.equal(imported.history[0].shapePolicy,policy);assert.deepEqual(imported.history[0].beautyNotes,['tetsu-sweep-end']);
assert.deepEqual(old.records.iron.history[0].beautyNotes,[]);
console.log('PASS: independently disabled direction/order/count/position, position tolerance, settings defaults, protrusion records and old-record migration');
